services:
  ejabberd:
    image: ejabberd/ecs
    platform: linux/amd64
    container_name: xmpp-ejabberd
    restart: unless-stopped
    ports:
      - "5280:5280"
      - "5222:5222"
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
